import type { CourseWeek } from './types';

export const WEEK_1: CourseWeek = {
  id: 'week-1',
  title: 'Неделя 1: база слепой печати',
  days: [
    {
      id: 'day-1',
      dayNumber: 1,
      title: 'Домашний ряд',
      goal: 'Поставить пальцы на фыва олдж и связать цвет пальца с клавишей.',
      exercises: [
        {
          id: 'day-1-intro',
          type: 'intro',
          title: 'Найди дом',
          description: 'Первые якоря: указательные пальцы на а и о.',
          focusKeys: ['а', 'о'],
          content: 'ааа ооо ао ао ааоо ооаа аоа оао',
          targetAccuracy: 90,
        },
        {
          id: 'day-1-home-left',
          type: 'drill',
          title: 'Левая рука',
          description: 'Фиксируем ф ы в а без спешки.',
          focusKeys: ['ф', 'ы', 'в', 'а'],
          content: 'ффф ыыы ввв ааа фы фв фа ыва фыв фыва',
          targetAccuracy: 90,
        },
        {
          id: 'day-1-home-right',
          type: 'drill',
          title: 'Правая рука',
          description: 'Фиксируем о л д ж и возвращение в домашний ряд.',
          focusKeys: ['о', 'л', 'д', 'ж'],
          content: 'ооо ллл ддд жжж ол од ож лдж олдж',
          targetAccuracy: 90,
        },
        {
          id: 'day-1-checkpoint',
          type: 'checkpoint',
          title: 'Мини-проверка дня',
          description: 'Собираем домашний ряд в один ритм.',
          focusKeys: ['ф', 'ы', 'в', 'а', 'о', 'л', 'д', 'ж'],
          content: 'фыва олдж фыва олдж ао ол ва ло фы дж',
          targetAccuracy: 90,
        },
      ],
    },
    {
      id: 'day-2',
      dayNumber: 2,
      title: 'Указательные пальцы',
      goal: 'Добавить п и р, закрепить переходы от а и о.',
      exercises: [
        {
          id: 'day-2-ap-or',
          type: 'drill',
          title: 'А-П и О-Р',
          description: 'Короткие переходы указательных пальцев.',
          focusKeys: ['а', 'п', 'о', 'р'],
          content: 'ап ап ап ор ор ор па па ро ро апор пора',
          targetAccuracy: 90,
        },
        {
          id: 'day-2-bigrams',
          type: 'bigrams',
          title: 'Первые связки',
          description: 'Учимся держать ровный ритм на частых переходах.',
          focusKeys: ['а', 'п', 'о', 'р'],
          content: 'ап ра ро па ар оп пор пар рап про пора',
          targetAccuracy: 90,
        },
        {
          id: 'day-2-words',
          type: 'words',
          title: 'Слова из базы',
          description: 'Печатаем короткие слова только из знакомых клавиш.',
          focusKeys: ['ф', 'ы', 'в', 'а', 'о', 'л', 'д', 'ж', 'п', 'р'],
          content: 'пара пора опора право двор провал жар дар',
          targetAccuracy: 90,
        },
      ],
    },
    {
      id: 'day-3',
      dayNumber: 3,
      title: 'Верхний ряд центр',
      goal: 'Добавить к е н г и научиться возвращаться в домашний ряд.',
      exercises: [
        {
          id: 'day-3-ke-ng',
          type: 'drill',
          title: 'К-Е и Н-Г',
          description: 'Движение вверх без потери домашней позиции.',
          focusKeys: ['к', 'е', 'н', 'г'],
          content: 'ккк еее ннн ггг ке ке нг нг ек гн',
          targetAccuracy: 90,
        },
        {
          id: 'day-3-bigrams',
          type: 'bigrams',
          title: 'Верхние связки',
          description: 'Связываем верхний ряд с а о р п.',
          focusKeys: ['к', 'е', 'н', 'г', 'а', 'о', 'р', 'п'],
          content: 'ка ко ре но пе га ак ок ер он кра гор',
          targetAccuracy: 90,
        },
        {
          id: 'day-3-words',
          type: 'words',
          title: 'Первые частые слова',
          description: 'Слова с верхним рядом и базовыми переходами.',
          focusKeys: ['к', 'е', 'н', 'г'],
          content: 'река нога окно кора гора рано поле дело',
          targetAccuracy: 90,
        },
      ],
    },
    {
      id: 'day-4',
      dayNumber: 4,
      title: 'Нижний ряд центр',
      goal: 'Добавить м и т ь, освоить переходы вниз.',
      exercises: [
        {
          id: 'day-4-mi-ty',
          type: 'drill',
          title: 'М-И и Т-Ь',
          description: 'Переходы вниз и возврат на домашний ряд.',
          focusKeys: ['м', 'и', 'т', 'ь'],
          content: 'ммм иии ттт ььь ми ми ть ть им ьт',
          targetAccuracy: 91,
        },
        {
          id: 'day-4-bigrams',
          type: 'bigrams',
          title: 'Нижние связки',
          description: 'Чередуем нижний ряд с базой.',
          focusKeys: ['м', 'и', 'т', 'ь', 'а', 'о'],
          content: 'ма мо ти то ми ом та от им ит том там',
          targetAccuracy: 91,
        },
        {
          id: 'day-4-words',
          type: 'words',
          title: 'Слова с нижним рядом',
          description: 'Короткие слова на новых переходах.',
          focusKeys: ['м', 'и', 'т', 'ь'],
          content: 'мир том мать тень тема море итог ритм',
          targetAccuracy: 91,
        },
      ],
    },
    {
      id: 'day-5',
      dayNumber: 5,
      title: 'Частые связки',
      goal: 'Наработать ст, но, пр, то, на без лишних движений.',
      exercises: [
        {
          id: 'day-5-st-no',
          type: 'bigrams',
          title: 'СТ и НО',
          description: 'Две частые связки для русского текста.',
          focusKeys: ['с', 'т', 'н', 'о'],
          content: 'ст ст ст но но но сто нос тон стон сто',
          targetAccuracy: 92,
        },
        {
          id: 'day-5-pr-to-na',
          type: 'bigrams',
          title: 'ПР, ТО, НА',
          description: 'Связки, которые быстро начнут встречаться в фразах.',
          focusKeys: ['п', 'р', 'т', 'о', 'н', 'а'],
          content: 'пр пр то то на на про рот она пора нора',
          targetAccuracy: 92,
        },
        {
          id: 'day-5-words',
          type: 'words',
          title: 'Слова из связок',
          description: 'Печатаем слова, а не отдельные буквы.',
          focusKeys: ['с', 'т', 'н', 'о', 'п', 'р', 'а'],
          content: 'старт стена страна просто право место настроение',
          targetAccuracy: 92,
        },
      ],
    },
    {
      id: 'day-6',
      dayNumber: 6,
      title: 'Фразы и точка',
      goal: 'Печатать короткие предложения с пробелом и точкой.',
      exercises: [
        {
          id: 'day-6-dot',
          type: 'drill',
          title: 'Точка',
          description: 'Точка справа в нижнем ряду, без заглавных букв.',
          focusKeys: ['.', ' '],
          content: 'а. о. дом. рот. море. пора. старт.',
          targetAccuracy: 92,
        },
        {
          id: 'day-6-service-words',
          type: 'words',
          title: 'Служебные слова',
          description: 'Короткие слова дают плавность фразам.',
          focusKeys: ['и', 'в', 'на', 'не', 'это'],
          content: 'и в не на я ты он она это как так от до',
          targetAccuracy: 92,
        },
        {
          id: 'day-6-sentences',
          type: 'sentences',
          title: 'Короткие фразы',
          description: 'Первый спокойный набор предложений.',
          focusKeys: ['.', ' '],
          content: 'это мой дом. там море. пора на старт. она не одна.',
          targetAccuracy: 92,
        },
      ],
    },
    {
      id: 'day-7',
      dayNumber: 7,
      title: 'Итог недели',
      goal: 'Собрать навык недели в контрольном тексте.',
      exercises: [
        {
          id: 'day-7-warmup',
          type: 'drill',
          title: 'Разогрев',
          description: 'Повторяем базовые переходы перед контрольным текстом.',
          focusKeys: ['ф', 'ы', 'в', 'а', 'о', 'л', 'д', 'ж', 'п', 'р', 'т', 'н'],
          content: 'фыва олдж ап ор ке нг ми ть ст но пр то на',
          targetAccuracy: 92,
        },
        {
          id: 'day-7-checkpoint',
          type: 'checkpoint',
          title: 'Контроль недели',
          description: 'Финальный текст: точность важнее скорости.',
          focusKeys: ['ф', 'ы', 'в', 'а', 'о', 'л', 'д', 'ж', 'п', 'р', 'т', 'н', 'м', 'и', '.'],
          content: 'это первая неделя. пальцы знают свои клавиши. я печатаю ровно и спокойно. точность важнее скорости.',
          targetAccuracy: 93,
          targetCpm: 90,
        },
      ],
    },
  ],
};

